// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// SECURITY NOTE: Firebase API keys (apiKey fields) are designed to be public
// and are embedded in the app binary. They identify your Firebase project but
// are NOT secrets. Real security is enforced via Firebase Security Rules.
// DO NOT commit real service account keys, database secrets, or private keys
// to version control. Use --dart-define or environment variables for those.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Returns [currentPlatform] or null for unsupported platforms (instead of
  /// throwing). Useful for testing and conditional initialization.
  static FirebaseOptions? get maybeCurrentPlatform {
    try {
      return currentPlatform;
    } on UnsupportedError {
      return null;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE_mWGG30vuRUF1IHA-u0Lp3_7d5bAWmg',
    appId: '1:362855889129:web:d78b260d8ccc6c45f31878',
    messagingSenderId: '362855889129',
    projectId: 'flutter-step-build',
    authDomain: 'flutter-step-build.firebaseapp.com',
    storageBucket: 'flutter-step-build.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCChKB8ezvJz93lij6xjukHPeZg1K_VFQ0',
    appId: '1:362855889129:android:c8b14e2f5aa8407bf31878',
    messagingSenderId: '362855889129',
    projectId: 'flutter-step-build',
    storageBucket: 'flutter-step-build.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjL1k4gMF6jPQIWOWaAwOf3lSmqJ6SA5A',
    appId: '1:362855889129:ios:b7fd8daf53d3993df31878',
    messagingSenderId: '362855889129',
    projectId: 'flutter-step-build',
    storageBucket: 'flutter-step-build.firebasestorage.app',
    iosBundleId: 'com.example.stepsRecoveryFlutter',
  );
}
