#Requires -Version 5.1
<#
.SYNOPSIS
    Runs the daily update routine
.DESCRIPTION
    Executes daily maintenance tasks:
    - Fetch latest documentation
    - Run knowledge integration
    - Create daily summary
    - Archive old learnings
.PARAMETER Force
    Force run even if already run today
.EXAMPLE
    .\daily-update.ps1
.EXAMPLE
    .\daily-update.ps1 -Force
#>

param(
    [switch]$Force
)

# Import utilities
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
. "$ScriptDir\utils\logger.ps1"

# Initialize
$LogPath = "$ScriptDir\..\logs\daily-update.log"
$LastRunFile = "$ScriptDir\..\logs\last-daily-run.txt"

Write-Log "Starting daily update routine" $LogPath

try {
    # Check if already run today
    if (-not $Force -and (Test-Path $LastRunFile)) {
        $lastRun = Get-Content $LastRunFile -Raw
        $lastRunDate = [DateTime]::Parse($lastRun.Trim())
        $today = Get-Date -Hour 0 -Minute 0 -Second 0
        
        if ($lastRunDate -ge $today) {
            Write-Log "Daily update already run today ($lastRun)" $LogPath
            Write-Host "Daily update already run today" -ForegroundColor Yellow
            exit 0
        }
    }
    
    Write-Host "`n=== Daily Update Routine ===" -ForegroundColor Cyan
    
    # 1. Fetch latest documentation
    Write-Host "`n[1/4] Fetching documentation..." -ForegroundColor Green
    & "$ScriptDir\fetch-docs.ps1" -All
    
    # 2. Run knowledge integration
    Write-Host "`n[2/4] Integrating knowledge..." -ForegroundColor Green
    & "$ScriptDir\integrate-knowledge.ps1"
    
    # 3. Sync memory
    Write-Host "`n[3/4] Syncing memory..." -ForegroundColor Green
    & "$ScriptDir\sync-memory.ps1"
    
    # 4. Create daily summary
    Write-Host "`n[4/4] Creating daily summary..." -ForegroundColor Green
    Create-DailySummary -LogPath $LogPath
    
    # Record last run
    Set-Content -Path $LastRunFile -Value (Get-Date -Format "yyyy-MM-dd HH:mm:ss") -Encoding UTF8
    
    Write-Host "`n=== Daily Update Complete ===" -ForegroundColor Green
    Write-Log "Daily update routine complete" $LogPath
}
catch {
    Write-Log "Error during daily update: $($_.Exception.Message)" $LogPath -Level Error
    Write-Host "Error: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

function Create-DailySummary {
    param(
        [string]$LogPath
    )
    
    $summaryDir = "$ScriptDir\..\logs\summaries"
    if (-not (Test-Path $summaryDir)) {
        New-Item -ItemType Directory -Path $summaryDir -Force | Out-Null
    }
    
    $today = Get-Date -Format "yyyy-MM-dd"
    $summaryFile = "$summaryDir\daily-$today.md"
    
    $summary = @"
# Daily Summary - $today

## Activities

### Documentation Fetch
- Sources updated: Flutter, Dart, Pub.dev packages

### Knowledge Integration
- Learnings integrated: $(Get-LearningCount -Type Integrated)
- Pending learnings: $(Get-LearningCount -Type Pending)

### Memory Sync
- Memory files updated
- Project state refreshed

## Logs

See: $LogPath

---
Generated by Self-Evolving Agent
"@
    
    $summary | Out-File -FilePath $summaryFile -Encoding UTF8
    Write-Host "  Daily summary created: $summaryFile" -ForegroundColor Gray
}

function Get-LearningCount {
    param(
        [ValidateSet('Integrated', 'Pending')]
        [string]$Type
    )
    
    $learningsFile = "$ScriptDir\..\knowledge\pending-learnings.json"
    
    if (Test-Path $learningsFile) {
        try {
            $learnings = Get-Content $learningsFile -Raw | ConvertFrom-Json
            
            if ($Type -eq 'Integrated') {
                return ($learnings | Where-Object { $_.Status -eq 'Integrated' }).Count
            } else {
                return ($learnings | Where-Object { $_.Status -ne 'Integrated' }).Count
            }
        }
        catch {
            return 0
        }
    }
    
    return 0
}
